In [3]:
import pandas as pd

In [4]:
df=pd.read_excel(r"C:\Users\rakes\Desktop\DataMites\Drive link\Projects\Capstone Project\Capstone Project_Customer data analysis\Customer_data_analysis_excel.xlsx")
print(df)

      invoice_no customer_id  gender  age    category  quantity    price  \
0        I100008     C199951    Male   65    Clothing         5  1500.40
1        I100014     C138893    Male   55   Cosmetics         5   203.30
2        I100015     C132779  Female   35    Clothing         2   600.16
3        I100024     C244411  Female   67       Books         3    45.45
4        I100027     C150002  Female   19  Technology         4  4200.00
...          ...         ...     ...  ...         ...       ...      ...
99452    I999956     C925896    Male   69        Toys         4   143.36
99453    I999959     C695980  Female   68    Clothing         4  1200.32
99454    I999972     C195931    Male   63  Technology         2  2100.00
99455    I999973     C248542    Male   28  Technology         1  1050.00
99456    I999994     C299697  Female   21  Technology         3  3150.00

      payment_method invoice_date      shopping_mall  Total_Sales
0               Cash   2022-07-10  Emaar Square Mall      7502.00
1               Cash   2021-06-18     Viaport Outlet      1016.50
2         Debit Card   2021-03-04   Mall of Istanbul      1200.32
3        Credit Card   2023-01-05  Emaar Square Mall       136.35
4               Cash   2022-05-18   Mall of Istanbul     16800.00
...              ...          ...                ...          ...
99452    Credit Card   2021-08-16          Metrocity       573.44
99453    Credit Card   2021-10-13             Kanyon      4801.28
99454     Debit Card   2021-01-23       Istinye Park      4200.00
99455    Credit Card   2023-01-11   Mall of Istanbul      1050.00
99456           Cash   2021-04-09             Kanyon      9450.00

[99457 rows x 11 columns]

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  datetime64[ns]
 9   shopping_mall   99457 non-null  object
 10  Total_Sales     99457 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 8.3+ MB
None

In [6]:
df.shape

(99457, 11)

In [7]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,Total_Sales
0,I100008,C199951,Male,65,Clothing,5,1500.40,Cash,2022-07-10,Emaar Square Mall,7502.00
1,I100014,C138893,Male,55,Cosmetics,5,203.30,Cash,2021-06-18,Viaport Outlet,1016.50
2,I100015,C132779,Female,35,Clothing,2,600.16,Debit Card,2021-03-04,Mall of Istanbul,1200.32
3,I100024,C244411,Female,67,Books,3,45.45,Credit Card,2023-01-05,Emaar Square Mall,136.35
4,I100027,C150002,Female,19,Technology,4,4200.00,Cash,2022-05-18,Mall of Istanbul,16800.00

In [8]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall',
       'Total_Sales'],
      dtype='object')

In [9]:
print(df.isnull().sum())

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
Total_Sales       0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [11]:
df.describe()

,age,quantity,price,invoice_date,Total_Sales
count,99457.000000,99457.000000,99457.000000,99457,99457.000000
mean,43.427089,3.003429,689.256321,2022-02-04 02:46:59.783424,2528.789268
min,18.000000,1.000000,5.230000,2021-01-01 00:00:00,5.230000
25%,30.000000,2.000000,45.450000,2021-07-19 00:00:00,136.350000
50%,43.000000,3.000000,203.300000,2022-02-05 00:00:00,600.170000
75%,56.000000,4.000000,1200.320000,2022-08-22 00:00:00,2700.720000
max,69.000000,5.000000,5250.000000,2023-03-08 00:00:00,26250.000000
std,14.990054,1.413025,941.184567,NaN,4222.475781

In [12]:
df['Total_Sales']=df['quantity']*df['price']
print(df)

      invoice_no customer_id  gender  age    category  quantity    price  \
0        I100008     C199951    Male   65    Clothing         5  1500.40
1        I100014     C138893    Male   55   Cosmetics         5   203.30
2        I100015     C132779  Female   35    Clothing         2   600.16
3        I100024     C244411  Female   67       Books         3    45.45
4        I100027     C150002  Female   19  Technology         4  4200.00
...          ...         ...     ...  ...         ...       ...      ...
99452    I999956     C925896    Male   69        Toys         4   143.36
99453    I999959     C695980  Female   68    Clothing         4  1200.32
99454    I999972     C195931    Male   63  Technology         2  2100.00
99455    I999973     C248542    Male   28  Technology         1  1050.00
99456    I999994     C299697  Female   21  Technology         3  3150.00

      payment_method invoice_date      shopping_mall  Total_Sales
0               Cash   2022-07-10  Emaar Square Mall      7502.00
1               Cash   2021-06-18     Viaport Outlet      1016.50
2         Debit Card   2021-03-04   Mall of Istanbul      1200.32
3        Credit Card   2023-01-05  Emaar Square Mall       136.35
4               Cash   2022-05-18   Mall of Istanbul     16800.00
...              ...          ...                ...          ...
99452    Credit Card   2021-08-16          Metrocity       573.44
99453    Credit Card   2021-10-13             Kanyon      4801.28
99454     Debit Card   2021-01-23       Istinye Park      4200.00
99455    Credit Card   2023-01-11   Mall of Istanbul      1050.00
99456           Cash   2021-04-09             Kanyon      9450.00

[99457 rows x 11 columns]

In [13]:
df['invoice_date']=pd.to_datetime(df['invoice_date'])
df['year']=df['invoice_date'].dt.year
df['month']=df['invoice_date'].dt.month
print(df)

      invoice_no customer_id  gender  age    category  quantity    price  \
0        I100008     C199951    Male   65    Clothing         5  1500.40
1        I100014     C138893    Male   55   Cosmetics         5   203.30
2        I100015     C132779  Female   35    Clothing         2   600.16
3        I100024     C244411  Female   67       Books         3    45.45
4        I100027     C150002  Female   19  Technology         4  4200.00
...          ...         ...     ...  ...         ...       ...      ...
99452    I999956     C925896    Male   69        Toys         4   143.36
99453    I999959     C695980  Female   68    Clothing         4  1200.32
99454    I999972     C195931    Male   63  Technology         2  2100.00
99455    I999973     C248542    Male   28  Technology         1  1050.00
99456    I999994     C299697  Female   21  Technology         3  3150.00

      payment_method invoice_date      shopping_mall  Total_Sales  year  month
0               Cash   2022-07-10  Emaar Square Mall      7502.00  2022      7
1               Cash   2021-06-18     Viaport Outlet      1016.50  2021      6
2         Debit Card   2021-03-04   Mall of Istanbul      1200.32  2021      3
3        Credit Card   2023-01-05  Emaar Square Mall       136.35  2023      1
4               Cash   2022-05-18   Mall of Istanbul     16800.00  2022      5
...              ...          ...                ...          ...   ...    ...
99452    Credit Card   2021-08-16          Metrocity       573.44  2021      8
99453    Credit Card   2021-10-13             Kanyon      4801.28  2021     10
99454     Debit Card   2021-01-23       Istinye Park      4200.00  2021      1
99455    Credit Card   2023-01-11   Mall of Istanbul      1050.00  2023      1
99456           Cash   2021-04-09             Kanyon      9450.00  2021      4

[99457 rows x 13 columns]

In [14]:
#Gender distribution
df['gender'].value_counts()

gender
Female    59482
Male      39975
Name: count, dtype: int64

In [15]:
#Category distribution
df['category'].value_counts()

category
Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: count, dtype: int64

In [16]:
#Payment method distribution
df['payment_method'].value_counts()

payment_method
Cash           44447
Credit Card    34931
Debit Card     20079
Name: count, dtype: int64

In [17]:
#Total sales
round(df['Total_Sales'].sum(),2)

np.float64(251505794.25)

In [18]:
#Sales by category
df.groupby('category')['Total_Sales'].sum().sort_values(ascending=False)

category
Clothing           1.139968e+08
Shoes              6.655345e+07
Technology         5.786235e+07
Cosmetics          6.792863e+06
Toys               3.980426e+06
Food & Beverage    8.495351e+05
Books              8.345529e+05
Souvenir           6.358247e+05
Name: Total_Sales, dtype: float64

In [19]:
#Sales by shopping mall
df.groupby('shopping_mall')['Total_Sales'].sum().sort_values()

shopping_mall
Forum Istanbul       12303921.24
Emaar Square Mall    12406100.29
Viaport Outlet       12521339.72
Cevahir AVM          12645138.20
Zorlu Center         12901053.82
Istinye Park         24618827.68
Metropol AVM         25379913.19
Metrocity            37302787.33
Kanyon               50554231.10
Mall of Istanbul     50872481.68
Name: Total_Sales, dtype: float64

In [20]:
#Sales by gender
gen_sales=df.groupby('gender')['Total_Sales'].sum()
gen_sales.apply(lambda x: f"{x:,.2f}")

gender
Female    150,207,136.02
Male      101,298,658.23
Name: Total_Sales, dtype: object

In [21]:
#Sales by year
yr_sales=df.groupby('year')['Total_Sales'].sum()
yr_sales.apply(lambda x:f"{x:,.2f}")

year
2021    114,560,570.59
2022    115,436,814.08
2023     21,508,409.58
Name: Total_Sales, dtype: object

In [22]:
#Sales by month
df.groupby('month')['Total_Sales'].sum()

month
1     28891525.59
2     26625090.10
3     21956191.33
4     18715685.98
5     19719331.10
6     18933775.30
7     20378722.63
8     19282361.29
9     18795794.91
10    20545090.43
11    18207139.95
12    19455085.64
Name: Total_Sales, dtype: float64

In [23]:
#Most sold categories
df.groupby('category')['quantity'].sum().sort_values(ascending=False)

category
Clothing           103558
Cosmetics           45465
Food & Beverage     44277
Toys                30321
Shoes               30217
Technology          15021
Books               14982
Souvenir            14871
Name: quantity, dtype: int64

In [24]:
#Category vs gender
df.groupby(['category','gender'])['Total_Sales'].sum()

category         gender
Books            Female      489314.70
                 Male        345238.20
Clothing         Female    68251695.60
                 Male      45745095.44
Cosmetics        Female     4066772.54
                 Male       2726090.36
Food & Beverage  Female      505322.60
                 Male        344212.45
Shoes            Female    39425167.30
                 Male      27128284.17
Souvenir         Female      382867.20
                 Male        252957.45
Technology       Female    34669950.00
                 Male      23192400.00
Toys             Female     2416046.08
                 Male       1564380.16
Name: Total_Sales, dtype: float64

In [25]:
#Payment method vs sales
pm_sales=df.groupby('payment_method')['Total_Sales'].sum().sort_values(ascending=False)
pm_sales.apply(lambda x:f"{x:,.2f}")

payment_method
Cash           112,832,243.02
Credit Card     88,077,123.77
Debit Card      50,596,427.46
Name: Total_Sales, dtype: object

In [26]:
#Task1 1 - How is the shopping distribution according to gender?
#based on count
df['gender'].value_counts()

#df['gender'].value_counts(normalize=True)*100

gender
Female    59482
Male      39975
Name: count, dtype: int64

In [27]:
#Task 2 - Which gender did we sell more products to?
df.groupby('gender')['quantity'].sum()

gender
Female    178659
Male      120053
Name: quantity, dtype: int64

In [30]:
#Task 3 - Which gender generated more revenue?
gen_sales=df.groupby('gender')['Total_Sales'].sum()
gen_sales.apply(lambda x:f"{x:,.2f}")

gender
Female    150,207,136.02
Male      101,298,658.23
Name: Total_Sales, dtype: object

In [40]:
#Task 4 - Distribution of purchase categories relative to other columns
#Category vs gender
pd.crosstab(df['category'],df['gender'])

#category vs payment method
pd.crosstab(df['category'],df['payment_method'])

#category vs shopping mall
pd.crosstab(df['category'],df['shopping_mall'])

#category vs sales
cat_sales=df.groupby('category')['Total_Sales'].sum().sort_values(ascending=False)
cat_sales.apply(lambda x:f"{x:,.2f}")

#Category vs quantity
df.groupby('category')['quantity'].sum()

#category vs age group
df['age_group']=pd.cut(df['age'],bins=[18,25,35,50,65],labels=['18-25','26-35','36-50','50+'])
pd.crosstab(df['category'],df['age_group'])

age_group        18-25  26-35  36-50   50+
category
Books              682    920   1443  1447
Clothing          4691   6614  10064  9837
Cosmetics         2009   2895   4379  4407
Food & Beverage   2025   2820   4304  4226
Shoes             1379   1928   2902  2904
Souvenir           660    970   1435  1460
Technology         662    962   1501  1411
Toys              1407   1950   2910  2838

In [49]:
#Task 5 - How is the shopping distribution according to age?
#number of purchses by age group
df['age_group'].value_counts().sort_values(ascending=False)

#Sales by age group
df.groupby('age_group',observed=True)['Total_Sales'].sum().sort_values(ascending=False)

#Quantity by age group
df.groupby('age_group',observed=True)['Total_Sales'].sum()

age_group
18-25    33720551.09
26-35    47879659.58
36-50    74199731.08
50+      72097258.12
Name: Total_Sales, dtype: float64

In [51]:
#Task 6 - Which age cat did we sell more products to?
df.groupby('age_group',observed=True)['quantity'].sum().sort_values(ascending=False)

age_group
36-50    86885
50+      85749
26-35    57265
18-25    40510
Name: quantity, dtype: int64

In [53]:
#Task 7 - Which age cat generated more revenue?
df.groupby('age_group',observed=True)['Total_Sales'].sum().sort_values(ascending=False)

age_group
36-50    74199731.08
50+      72097258.12
26-35    47879659.58
18-25    33720551.09
Name: Total_Sales, dtype: float64

In [62]:
#Task 8 - Does the payment method have a relation with other columns?
#Payment method distribution
df['payment_method'].value_counts()

#payment method vs gender
pd.crosstab(df['gender'],df['payment_method'],normalize='columns')*100

#payment method vs category
pd.crosstab(df['category'],df['payment_method'])

#payment method vs age group
pd.crosstab(df['age_group'],df['payment_method'])

#payment method vs sales
pay_sales=df.groupby('payment_method')['Total_Sales'].sum().sort_values(ascending=False)
pay_sales.apply(lambda x:f"{x:,.2f}")

#payment method vs shopping mall
pd.crosstab(df['shopping_mall'],df['payment_method'])

payment_method     Cash  Credit Card  Debit Card
shopping_mall
Cevahir AVM        2228         1779         984
Emaar Square Mall  2114         1696        1001
Forum Istanbul     2183         1750        1014
Istinye Park       4436         3422        1923
Kanyon             8853         6916        4054
Mall of Istanbul   8894         7019        4030
Metrocity          6625         5347        3039
Metropol AVM       4559         3521        2081
Viaport Outlet     2231         1721         962
Zorlu Center       2324         1760         991

In [64]:
#Task 9 - How is the distribution of the payment method?
#count distribution
df['payment_method'].value_counts()

#percentage distribution
df['payment_method'].value_counts(normalize=True)*100

payment_method
Cash           44.689665
Credit Card    35.121711
Debit Card     20.188624
Name: proportion, dtype: float64